# Site settings
title: tstesco
description: Some projects and thoughts on buildings, tech, and our cybernetic lives.

url: http://tstesco.github.io

about_title: About
projects_title: Projects

# User settings
user_description_appendix: |
  My interests are in systems engineering for virtuous feedback loops between 
  smart machines, people, and their environment.
  I'm currently working on adaptive human-in-the-loop building control using 
  probabilitstic programming to save energy and improve thermal comfort at the 
  [Automatic Control Lab](http://control.ee.ethz.ch/) within the 
  Information Technology and Electrical Engineering ([ITET](https://www.ee.ethz.ch/)) department.
  If these topics interest you feel free to get in contact over email.

email: tom.stesco@gmail.com
linkedin: tomstesco
github: tstesco
angellist: tom-stesco

relevant_tags: ['hardware', 'software', 'buildings']

resume_url: 

author: Tom Stesco
author_title: Integrated Building Systems MSc Candidate, ETH Zürich
author_photo: profile-photo-zh.jpg
user_description_short: |
  I'm a Master student at ETH Zürich originally from Canada. I did my undergrad at University of Waterloo and now 
  live in Switzerland pursuing a MSc degree in 
  [Integrated Building Systems](http://www.master-buildingsystems.ethz.ch/) 
  with the ETH
  [Excellence Scholarship & Opportunity Programme](https://www.ethz-foundation.ch/en/excellence-scholarships/).

## Disqus (commented out to disable)
#disqus_identifier: xxxx

## Tracker
google_analytics_id: UA-119019898-1

keywords: 'software,hardware,engineer,cybernetics,buildings,cities,design,'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']