# Site settings
title: Tom Stesco
description: Some projects and thoughts on buildings, tech, and our cybernetic lives.

url: https://tomstesco.com

about_title: About
projects_title: Projects

# User settings
user_description_appendix: |
  I'm currently working at the intersection of building physics simulation, machine learning in control systems, and distributed optimization on edge devices.
  If these topics interest you feel free to get in contact over email.

email: tom.stesco@gmail.com
linkedin: tomstesco
github: tstesco
resume: tstesco_resume_2022.pdf

relevant_tags: ['hardware', 'software', 'buildings']

resume_url: 

author: Tom Stesco
author_title: Senior AI/ML Engineer @ BCG X

author_photo: profile-photo-zh.jpg
user_description_short: |
  I'm a Senior AI/ML Engineer at [BCG X](https://www.bcg.com/x){:target="_blank"}, living in Toronto Canada.
  I went to school at ETH Zürich (MSc) and University of Waterloo (BASc).
  My interests are in AI/ML for virtuous feedback between machines, people, and their environment.

highlighter: pygments.rb
markdown: kramdown
## Disqus (commented out to disable)
#disqus_identifier: xxxx

## Tracker
google_analytics_id: UA-119019898-1

keywords: 'software,hardware,engineer,AI,ML,machine learning,cybernetics,buildings,cities,design,'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']