# Site settings
title: Tom Stesco
description: Some projects and thoughts on buildings, tech, and our cybernetic lives.

url: https://tomstesco.com

about_title: About
projects_title: Projects

# User settings
user_description_appendix: |
  I'm currently working at the intersection of building physics simulation, machine learning in control systems, and distributed optimization on edge devices.
  If these topics interest you feel free to get in contact over email.

email: tom.stesco@gmail.com
linkedin: tomstesco
github: tstesco
resume: tom_stesco_resume.pdf

relevant_tags: ['hardware', 'software', 'buildings']

resume_url: 

author: Tom Stesco
author_title: Senior Data Scientist @ ecobee
author_photo: profile-photo-zh.jpg
user_description_short: |
  I'm a senior data scientist at [ecobee](https://www.ecobee.com/), living in Toronto Canada.
  I went to school at ETH Zürich (MSc) and University of Waterloo (BASc).
  My interests are in systems engineering for virtuous feedback loops between learning machines, people, and their environment.

## Disqus (commented out to disable)
#disqus_identifier: xxxx

## Tracker
google_analytics_id: UA-119019898-1

keywords: 'software,hardware,engineer,cybernetics,buildings,cities,design,'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']