# Site settings
title: Tom Stesco
description: Some projects and thoughts on buildings, tech, and our cybernetic lives.

url: https://tomstesco.com

about_title: About
projects_title: Projects

# User settings
user_description_appendix: |
  I'm currently working at the intersection of building physics simulation, machine learning in control systems, and distributed optimization on edge devices.
  If these topics interest you feel free to get in contact over email.

email: tom.stesco@gmail.com
linkedin: tomstesco
github: tstesco
angellist: tom-stesco

relevant_tags: ['hardware', 'software', 'buildings']

resume_url: 

author: Tom Stesco
author_title: Data Scientist @ ecobee
author_photo: profile-photo-zh.jpg
user_description_short: |
  I'm a data scientist and control research engineer at [ecobee](https://www.ecobee.com/), born and living in Toronto Canada.
  I did my MSc at ETH Zürich in [Integrated Building Systems](http://www.master-buildingsystems.ethz.ch/) after finishing my BASc at University of Waterloo.
  My overarching interests are in systems engineering for virtuous feedback loops between smart machines, people, and their environment.

## Disqus (commented out to disable)
#disqus_identifier: xxxx

## Tracker
google_analytics_id: UA-119019898-1

keywords: 'software,hardware,engineer,cybernetics,buildings,cities,design,'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']